// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOr0K6duc4Ufqmb8pXJxqhnYY_qaHYodE',
    appId: '1:951333086712:web:0ddb11f40ddfe564ca620d',
    messagingSenderId: '951333086712',
    projectId: 'dia-eventos-project',
    authDomain: 'dia-eventos-project.firebaseapp.com',
    storageBucket: 'dia-eventos-project.firebasestorage.app',
    measurementId: 'G-5JBTJ852W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQSmnTm0_QmA1DgKkgKoUSzC5I9i7KGE',
    appId: '1:951333086712:android:46a50a02e122eadeca620d',
    messagingSenderId: '951333086712',
    projectId: 'dia-eventos-project',
    storageBucket: 'dia-eventos-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg3gKZmqRVMrBGPla1i48LHdmXmwYkjQA',
    appId: '1:951333086712:ios:2d7de3fddee94807ca620d',
    messagingSenderId: '951333086712',
    projectId: 'dia-eventos-project',
    storageBucket: 'dia-eventos-project.firebasestorage.app',
    iosBundleId: 'com.diaeventos.ec.mainDiaeventos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg3gKZmqRVMrBGPla1i48LHdmXmwYkjQA',
    appId: '1:951333086712:ios:2d7de3fddee94807ca620d',
    messagingSenderId: '951333086712',
    projectId: 'dia-eventos-project',
    storageBucket: 'dia-eventos-project.firebasestorage.app',
    iosBundleId: 'com.diaeventos.ec.mainDiaeventos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOr0K6duc4Ufqmb8pXJxqhnYY_qaHYodE',
    appId: '1:951333086712:web:df11dd76455c8193ca620d',
    messagingSenderId: '951333086712',
    projectId: 'dia-eventos-project',
    authDomain: 'dia-eventos-project.firebaseapp.com',
    storageBucket: 'dia-eventos-project.firebasestorage.app',
    measurementId: 'G-QSCRD29X5V',
  );
}
